export const NUMBER_OF_SECONDS_PER_HOURS = 3600;
export const NUMBER_OF_MINUTES_PER_HOURS = 60;
export const NUMBER_OF_SECONDS_PER_MINUTES = 60;
export const NUMBER_OF_MILLISECONDS_PER_HOURS = 3600000;
export const AVERAGE_NUMBER_OF_DAYS_PER_MONTHS = 30;
export const NUMBER_OF_MONTHS_PER_YEARS = 12;
export const NUMBER_OF_HOURS_PER_DAYS = 24;

export const NUMBER_OF_MILLISECONDS_PER_DAYS = NUMBER_OF_MILLISECONDS_PER_HOURS * NUMBER_OF_HOURS_PER_DAYS;
export const AVERAGE_NUMBER_OF_MILLISECONDS_PER_MONTHS =
  NUMBER_OF_MILLISECONDS_PER_DAYS * AVERAGE_NUMBER_OF_DAYS_PER_MONTHS;

export const AVERAGE_NUMBER_OF_MILLISECONDS_PER_YEARS =
  AVERAGE_NUMBER_OF_MILLISECONDS_PER_MONTHS * NUMBER_OF_MONTHS_PER_YEARS;

export const API_BASE_URL = `${process.env.REACT_APP_API_URL}/${process.env.REACT_APP_API_VERSION}`;
